name: photosync
version: 1.2.0+5
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 跨平台共享
  photosync_common:
    path: ../common
  # 状态管理
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  # 网络
  dio: ^5.4.0
  udp: ^5.0.3
  http: ^1.1.0
  # 相册访问
  photo_manager: ^3.9.0
  photo_manager_image_provider: ^2.2.0
  image_picker: ^1.0.7
  # UI
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  # 工具
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  crypto: ^3.0.3
  image: ^4.1.3
  # 二维码
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  # 权限
  permission_handler: ^11.1.0
  # 网络状态
  connectivity_plus: ^5.0.2
  # 应用信息
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
